services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - .:/app
      - ./logs/app:/var/log/app
    command: >
      gunicorn app:app -k uvicorn.workers.UvicornWorker --workers 4 --bind 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      - presidio-analyzer
    labels:
      - logging=promtail
    environment:
      - POSTGRES_HOST=db

  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer
    ports:
      - "5100:5001"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8100:80"  # External port is now 8100
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: ankane/pgvector:latest  # <-- pgvector-enabled PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensitivescan
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
