global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['app:8000']
  - job_name: 'locust'
    static_configs:
      - targets: ['locust:8089']
